language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
  - "10"
  - "12"
after_script:
  - npm run coverage
branches:
  only:
  - dev
  - npm
  - v3-lts
  # After releasing, bump to next anticpated version.
  - v3-lts@3.0.7
